### PR TITLE
v1.100: Added build chain and mastered fonts

### PR DESCRIPTION
**Pull request by m4rc1e**
- Fonts now pass fontbakery
- Build chain will make ttf, otf, eot, woff and woff2
- Updated README.md to include build instructions.
- Include OFL.txt

### CODE REVIEW

**Comment by davelab6** [comment]
Looks good to me

**Comment by davelab6** [comment]
Ah, RFN is mentioned in README, needs to be dropped :)

**Comment by m4rc1e** [comment]
Done ;-)

**Comment by m4rc1e** [comment]
ping @Lacquer-Font

**Comment by Lacquer-Font** [comment]
Merged! Sorry that took so long! Is there anything else you need me to do?

**Pull request merged**
